// Generic class to maintain all thr constants used throughout the project in KM.
public with sharing class KM_Constants {

    public static final String AUTHOR_PROFILE = 'Minimum Access Admin';
    public static final String AGENT_PROFILE = 'Minimum Access Agent';
    public static final String AUTO_PUBLISH_PERM_AUTHOR_GROUP = 'Auto Publish Permission Authors';
    public static final String SPONSER_POST_FIX = '@att.com%';
    public static final String PRIM_CONTENT_SPONSER = 'Primary Content Sponsor';
    public static final String SEC_CONTENT_SPONSER = 'Secondary Content Sponsor';
    public static final String CONTENT_SPONSER_INVALID_ATTUID_ERROR_MESSAGE = 'No active author found/Invalid ATTUID';
    public static final String SME_INSERT_RECORD_ERROR_MESSAGE = 'There was a problem adding the SME records. Contact the System Administrator';
    public static final String ARTICLE_COPY_ERROR_MESSAGE = 'Error carrying over previous article information.  Please contact the administrator.';
    public static final String SME_CONSTANT='SME';
    public static final String RESOLVED = 'Resolved';
    public static final String REASON_ARTICLE_LIKE = 'I Like This Article, because';

}