/*********
Name        : TestDataFactoryTest
*******/

@isTest
public class TestDataFactoryTest{
    
/*    public static testmethod void testUnit(){
        Knowledge__kav knowledgekav = KM_TestDataFactory.getKnowledKav(system.today(),'test','testurl',true);
        //Get RecordTypeId.
        Id newsArticleRecordTypeId = Schema.SObjectType.Knowledge__kav.getRecordTypeInfosByName().get('News Article').getRecordTypeId();  
        //Create Record for RecordTypeName 'News Article'.
        Knowledge__kav knowledKavTest= KM_TestDataFactory.getKnowledKavTest(newsArticleRecordTypeId ,System.Now().AddDays(5),'testone','testing',true);
        Knowledge__kav knowledKavTest2= KM_TestDataFactory.getKnowledKavdata(system.today(),'test','testurlnew',true);
        Knowledge__kav knowledge_fontline = KM_TestDataFactory.getKnowledKavfronlinefocus(newsArticleRecordTypeId ,
                            System.Now().AddDays(5),
                            'testonefontline',
                            'testingfontline',
                            true);
        Knowledge__kav knowledKavDataForDeleteArchiveBat= KM_TestDataFactory.getKnowledKavDataForDeleteArchiveBat(system.today(),System.today().AddDays(-2),'test','testurlbat',true);
    } */
}