import * as RAISR_API from "c/bwcRaisrAPI";

export const RAISR_FIELD_TYPE = Object.freeze({
  CREDIT_CARD:    RAISR_API.RAISR_FIELD_TYPE.CREDIT_CARD_NUMBER,
  ZIP:            RAISR_API.RAISR_FIELD_TYPE.CEDIT_CARD_ZIP,
  EXP_DATE:       RAISR_API.RAISR_FIELD_TYPE.CREDIT_CARD_EXP_DATE,
  CVV:            RAISR_API.RAISR_FIELD_TYPE.CREDIT_CARD_CVV,
  BANK_ACC:       RAISR_API.RAISR_FIELD_TYPE.BANK_ACC_NUMBER,
  BANK_ROUTING:   RAISR_API.RAISR_FIELD_TYPE.BANK_ROUTING_NUMBER
});